@hostAddress = http://localhost:5476
# Get the weather
GET {{hostAddress}}/weatherforecast


###

# Get claim history
GET {{hostAddress}}/customers/32-445-8382/claims/history

###
GET {{hostAddress}}/customers/123/claims/history

###

GET {{hostAddress}}/api/customers/456/claims/history