GET http://localhost:7071/api/AgentOrchestrator_HttpStart

###

GET http://localhost:7071/runtime/webhooks/durabletask/instances/3c21b123d21c4ec49a944df545e7dd7b?code=r7mgcrHYDYCBx1zEIMH4ZhWxWrWjffsrWh0tzDOeHilZAzFu-6e_Qw==