POST http://localhost:7071/api/StartClaimProcess
Content-Type: application/json

{
  "ClaimId": "789001",
  "PolicyNumber": "POLICY-67890",
  "ClaimantName": "John Doe",
  "ClaimantContact": "john.doe@example.com",
  "DateOfAccident": "2023-01-01",
  "AccidentDescription": "Minor fender bender.",
  "VehicleMake": "Toyota",
  "VehicleModel": "Camry",
  "VehicleYear": 2020,
  "LicensePlate": "ABC123",
  "AmountClaimed": 1000.00,
  "Status": 1
}


###

GET http://localhost:7071/runtime/webhooks/durabletask/instances/45075285c07f4b2b960e8af42c82dfda?code=9VTO3HYNWfKU-yOSsK5QOw0yitxF4Ix-Zj5Q0zuFGK0pAzFuyxx72w==

###
GET http://localhost:7071/api/claims/status/9fbc97925b1c4e3f9bd9d31802499238